markdown: kramdown
rouge: true
permalink: pretty
exclude: ['README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'CNAME', 'config.codekit', 'prepros.config']
gems:
  - jekyll-paginate-v2

# Pagination Settings
pagination:
  enabled: true
  per_page: 1
  limit: 1
